### PR TITLE
List BSD license in footer (Fix #283)

### LINKED ISSUE #283: copyright statement misleading
Hi @jburel et al,

I was just collecting information about licenses of training materials and here in this repository I was a little bit confused. In the github repository exists a [BSD 2 license file](https://github.com/ome/omero-guides/blob/master/LICENSE.md) but on the bottom of the [rendered page](https://omero-guides.readthedocs.io/en/latest/) it says:

image

Would it be possible to show the right license in the rendered website? That way it would be easier to **R**euse the materials following the FAIR principles.

Thanks!

best,
Robert

### PR DESCRIPTION
**Pull request by joshmoore**
Came back across this after seeing https://github.com/NFDI4BIOIMAGE/licensing/issues/1

### CODE REVIEW

**Comment by joshmoore** [comment]
image


cc: @haesleinhuepf ❓

**Comment by haesleinhuepf** [comment]
Looks great @joshmoore ! Optional: Add a link to the license.

**Comment by joshmoore** [comment]
I'm not sure it will render in that location, but I'll try it out.

**Comment by joshmoore** [comment]
@haesleinhuepf: no luck.

**Comment by haesleinhuepf** [comment]
That's fine. 🤷🌞

**Comment by jburel** [comment]
following the ome community meeting, we discussed changing the license to creative common.
I did not have a chance to get around that

**Comment by joshmoore** [comment]
np. But I assume this can't hurt until you get around to that, eh?

**Comment by joshmoore** [comment]
@jburel : are you ok if one of us merges this?

**Pull request merged**
