### PR TITLE
Facility manager walkthrough new

### PR DESCRIPTION
**Pull request by jburel**
This PR replaces #12

### CODE REVIEW

**Comment by pwalczysko** [comment]
```
/Users/pwalczysko/Work/omero-guides/external_tools.rst:37: WARNING: Duplicate target name, cannot be used as a unique reference: "trackmate".
```

I am having in the local build the above error, but the trackmate workflow is accessible from the top doc.

**Comment by jburel** [comment]
I won't worry about that in this PR, I will investigate it

**Comment by pwalczysko** [comment]
Screen Shot 2020-07-08 at 11 03 01

:)

**Comment by pwalczysko** [comment]
Do you want me to push a fix for the [problem in Facility manager walkthrough](https://github.com/ome/omero-guides/pull/14#issuecomment-655422151) ?

**Comment by jburel** [comment]
Sorry which problem, easier if you push to this branch

**Comment by pwalczysko** [comment]
> Sorry which problem, easier if you push to this branch

You fixed it already in https://github.com/ome/omero-guides/pull/14/commits/ec20c21f97ce0f4f36f78198d81809357a2c01f9

**Comment by pwalczysko** [comment]
Looks good to me. I think we can merge. Thank you

**Pull request merged**
